'use client'
import {useEffect,useState} from 'react'
import {parts} from '../../data'

export default function CartClient(){
 const [items,setItems]=useState([]);useEffect(()=>{setItems(JSON.parse(localStorage.getItem('cart')||'[]'))},[]);function save(v){setItems(v);localStorage.setItem('cart',JSON.stringify(v))}
 const rows=items.map(i=>({...i,part:parts.find(p=>p.sku===i.sku)})).filter(r=>r.part);const total=rows.reduce((s,r)=>s+Number(String(r.part.price).replace(/\D/g,''))*r.qty,0);
 function upd(sku,qty){if(qty<1)save(items.filter(i=>i.sku!==sku));else save(items.map(i=>i.sku===sku?{...i,qty}:i))}
 function checkout(mode='part'){const text=rows.map(r=>`${r.part.name} ${r.sku} x${r.qty}`).join('\n');sessionStorage.setItem('orderDraft',`${mode==='install'?'Записать на установку с деталями':'Заказ запчастей'}:\n${text}\nОриентировочно: ${total} ₽`);location.href='/contact'}
 return <><section className="hero"><span className="badge">Мой подбор</span><h1>Подбор деталей</h1><p>Это не онлайн-оплата. Здесь собраны детали для заявки менеджеру: он проверит наличие, цену и возможность установки.</p></section>{!rows.length&&<section className="section card emptyState"><h2>Список подбора пуст</h2><p className="muted">Добавьте запчасти из каталога или проверьте наличие по артикулу.</p><a className="btn primary" href="/parts">Открыть каталог</a> <a className="btn" href="/availability">Проверить наличие</a></section>}{rows.length>0&&<div className="section split"><section>{rows.map(r=><article className="card" key={r.sku}><h2>{r.part.name}</h2><p className="muted">{r.sku} · {r.part.price}</p><p>Количество: <button className="btn" onClick={()=>upd(r.sku,r.qty-1)}>-</button> <b>{r.qty}</b> <button className="btn" onClick={()=>upd(r.sku,r.qty+1)}>+</button></p></article>)}</section><aside className="card"><h2>Заявка по подбору</h2><p className="total">{total} ₽</p><p className="muted">Финальная цена и наличие подтверждаются менеджером.</p><button className="btn primary" onClick={()=>checkout('part')}>Заказать запчасти</button><button className="btn" onClick={()=>checkout('install')}>Записаться на установку</button></aside></div>}</>}
