'use client'
import Link from 'next/link'
import {useMemo,useState} from 'react'
import {parts} from '../../data'

export default function PartsClient(){
 const [q,setQ]=useState('');const [msg,setMsg]=useState('');const list=useMemo(()=>{const s=q.toLowerCase().trim();return !s?parts:parts.filter(p=>(p.name+p.sku+p.compatibility+p.category).toLowerCase().includes(s))},[q]);
 function add(p){const cart=JSON.parse(localStorage.getItem('cart')||'[]');const item=cart.find(x=>x.sku===p.sku);if(item)item.qty+=1;else cart.push({sku:p.sku,qty:1});localStorage.setItem('cart',JSON.stringify(cart));setMsg(`${p.name} добавлен в подбор`)}
 function request(p,mode='part'){sessionStorage.setItem('orderDraft',`${mode==='install'?'Записать на установку':'Заказать запчасть'}:\n${p.name}\nАртикул: ${p.sku}\nЦена: ${p.price}\nСовместимость: ${p.compatibility}`);location.href='/contact'}
 return <><section className="hero"><span className="badge">Каталог</span><h1>Популярные запчасти</h1><p>Каталог помогает быстро выбрать позицию. Актуальное наличие и цену лучше проверить по артикулу.</p></section><div className="sectionHead section"><div><h2>Каталог запчастей</h2><p className="muted">Поиск по названию, артикулу, категории или совместимости.</p></div><input className="input" style={{maxWidth:360}} value={q} onChange={e=>setQ(e.target.value)} placeholder="Поиск запчасти"/></div>{msg&&<p className="notice">{msg}</p>}<div className="grid">{list.map(p=><article className="card" key={p.sku}><span className="badge">{p.category}</span><h2>{p.name}</h2><p className="muted">Артикул: {p.sku}</p><p>{p.compatibility}</p><p className="stock">В наличии: {p.stock} шт.</p><p className="price">{p.price}</p><div className="cardActions"><button className="btn primary" onClick={()=>request(p,'part')}>Заказать</button><button className="btn" onClick={()=>request(p,'install')}>Установить</button><button className="btn" onClick={()=>add(p)}>В подбор</button><Link className="btn" href={`/availability?q=${encodeURIComponent(p.sku)}`}>Проверить</Link></div></article>)}</div></>}
